"""test

Revision ID: 1ef37c752fb7
Revises: 342e23a96772
Create Date: 2023-06-18 18:41:46.729830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ef37c752fb7'
down_revision = '342e23a96772'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_reservations_location_id_locations'), 'locations', ['location_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_reservations_customer_id_customers'), 'customers', ['customer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_reservations_customer_id_customers'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_reservations_location_id_locations'), type_='foreignkey')
        batch_op.drop_column('customer_id')
        batch_op.drop_column('location_id')

    # ### end Alembic commands ###
