"""models updated

Revision ID: a0cae90ac80d
Revises: a7306be7419a
Create Date: 2023-06-19 11:27:37.177345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0cae90ac80d'
down_revision = 'a7306be7419a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.alter_column('party_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('party_size',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.alter_column('party_size',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('party_name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
