"""models updated

Revision ID: a7306be7419a
Revises: b458deeddfa3
Create Date: 2023-06-19 10:08:11.249293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7306be7419a'
down_revision = 'b458deeddfa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_reservations_location_id'), ['location_id', 'customer_id', 'reservation_date'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_reservations_location_id'), type_='unique')

    # ### end Alembic commands ###
