"""models updated

Revision ID: b458deeddfa3
Revises: 2983b750a7ff
Create Date: 2023-06-19 10:07:30.373836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b458deeddfa3'
down_revision = '2983b750a7ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_constraint('uq_reservations_location_id', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_reservations_location_id', ['location_id', 'customer_id', 'reservation_date'])

    # ### end Alembic commands ###
